language: ruby

dist: bionic

rvm:
  - 2.7.0

branches:
  only:
    - master

jobs:
  include:
    - name: "Test"
      script: bundle exec rspec
    - name: "Rubocop"
      script: bundle exec rubocop
