language: ruby

rvm:
  - 2.6.6

branches:
  only:
    - master
    - /SB-\d*-/

jobs:
  include:
    - name: "Test"
      script: bundle exec rspec
    - name: "Rubocop"
      script: bundle exec rubocop
